import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import Context from "./components/Context";


export const metadata: Metadata = {
  title: "Portfolio hajhouj",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{scrollBehavior:"smooth"}}>
         <body
            style={{background:"#f9fafb"}}
            className={`w-full relative!  min-h-screen   text-gray-950  m-0  `}
          >

        
        <Context>

          <Header></Header>
          {children}
          <Footer></Footer>

        </Context>
        
        </body>
    </html>
  );
}
